POST http://localhost:8080/message
Content-Type: application/json

{
  "text": "MMM!"
}

###

GET http://localhost:8080/messages

###

GET http://localhost:8080/message/75d0b994-0bcf-4a3d-a549-56cf49973525